import {
    Activity,
    AlertTriangle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Battery,
    Bell,
    BookOpen,
    Building2,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronRight,
    Cloud,
    Code,
    Cpu,
    Database,
    Download,
    Droplets,
    ExternalLink,
    Factory,
    Globe,
    GraduationCap,
    HardHat,
    Headphones,
    Heart,
    Image as ImageIcon,
    Landmark,
    Leaf,
    Mail,
    MapPin,
    Newspaper,
    Package,
    Phone,
    Plane,
    Play,
    Radio,
    RefreshCw,
    Rocket,
    Search,
    Shield,
    Ship,
    ShoppingBag,
    ShoppingCart,
    Sparkles,
    Star,
    Stethoscope,
    Thermometer,
    Tractor,
    Truck,
    Users,
    Wheat,
    Zap,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/**
 * String → LucideIcon lookup for CMS content (icons stored as PascalCase
 * lucide-react export names in section JSON). Keep this list aligned with
 * the icon options in Filament resource Selects (icon_name fields).
 *
 * To add a new icon: import it above, add it to the map below, and add
 * it to the matching Filament Select options array.
 */
export const LUCIDE_ICON_MAP: Record<string, LucideIcon> = {
    Activity,
    AlertTriangle,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    Battery,
    Bell,
    BookOpen,
    Building2,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronRight,
    Cloud,
    Code,
    Cpu,
    Database,
    Download,
    Droplets,
    ExternalLink,
    Factory,
    Globe,
    GraduationCap,
    HardHat,
    Headphones,
    Heart,
    Image: ImageIcon,
    Landmark,
    Leaf,
    Mail,
    MapPin,
    Newspaper,
    Package,
    Phone,
    Plane,
    Play,
    Radio,
    RefreshCw,
    Rocket,
    Search,
    Shield,
    Ship,
    ShoppingBag,
    ShoppingCart,
    Sparkles,
    Star,
    Stethoscope,
    Thermometer,
    Tractor,
    Truck,
    Users,
    Wheat,
    Zap,
};

export function lucideIcon(name?: string | null): LucideIcon | null {
    if (!name) {
        return null;
    }

    return LUCIDE_ICON_MAP[name] ?? null;
}
